apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oathkeeper-stack.fullname" . }}-oathkeeper
  labels:
    {{- include "oathkeeper-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: oathkeeper
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "oathkeeper-stack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: oathkeeper
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "oathkeeper-stack.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: oathkeeper
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "oathkeeper-stack.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: oathkeeper
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.oathkeeper.image.repository }}:{{ .Values.oathkeeper.image.tag }}"
          imagePullPolicy: {{ .Values.oathkeeper.image.pullPolicy }}
          args:
            - serve
            - proxy
            - -c
            - /etc/config/oathkeeper/oathkeeper.yml
          env:
            - name: LOG_LEVEL
              value: debug
          ports:
            - name: proxy
              containerPort: 4455
              protocol: TCP
            - name: api
              containerPort: 4456
              protocol: TCP
          volumeMounts:
            - name: oathkeeper-config
              mountPath: /etc/config/oathkeeper
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: oathkeeper-config
          configMap:
            name: {{ include "oathkeeper-stack.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
