# Default values for myapp.
replicaCount: 1

image:
  repository: myapp-02
  pullPolicy: Never
  tag: "v1"

imagePullSecrets: []
nameOverride: "myapp-02"
fullnameOverride: "myapp-02"

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Oathkeeper access rules configuration
oathkeeper:
  enabled: true
  rules:
    api:
      enabled: true
      name: "myapp-02-api-rule"
      urlPattern: "<https|http>://<.*>/myapp-02/v1<.*>"
      methods: ["GET", "POST", "PUT", "PATCH", "DELETE"]
      authenticator:
        handler: bearer_token
      authorizer:
        handler: allow
      mutator:
        handler: header
