apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: auth-server
  namespace: default
spec:
  releaseName: auth-server
  chart:
    spec:
      chart: ./helm/auth-server
      sourceRef:
        kind: GitRepository
        name: auth-poc
        namespace: flux-system
  interval: 5m
  install:
    createNamespace: true
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: auth-server
      tag: v1
      pullPolicy: Never
    service:
      type: NodePort
      port: 3000
      nodePort: 30000
