apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oathkeeper-maester
  namespace: ory
spec:
  releaseName: oathkeeper-maester
  chart:
    spec:
      chart: oathkeeper-maester
      version: "0.1.9"
      sourceRef:
        kind: HelmRepository
        name: ory
        namespace: flux-system
  interval: 5m
  install:
    createNamespace: true
  upgrade:
    remediation:
      retries: 3
