apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oathkeeper
  namespace: ory
spec:
  releaseName: oathkeeper
  chart:
    spec:
      chart: oathkeeper
      version: "0.40.6"
      sourceRef:
        kind: HelmRepository
        name: ory
        namespace: flux-system
  interval: 5m
  install:
    createNamespace: true
  upgrade:
    remediation:
      retries: 3
  values:
    maester:
      enabled: true
    oathkeeper:
      managedAccessRules: false
      config:
        log:
          level: debug
          format: json
          leak_sensitive_values: true
        serve:
          proxy:
            cors:
              enabled: false
        errors:
          fallback:
            - json
          handlers:
            json:
              enabled: true
              config:
                verbose: true
        access_rules:
          matching_strategy: regexp
          repositories:
            - inline://oathkeeper-rules
        authenticators:
          anonymous:
            enabled: true
            config:
              subject: guest
          bearer_token:
            enabled: true
            config:
              check_session_url: http://auth-server.default.svc.cluster.local:3000/sessions/whoami
              preserve_path: true
              extra_from: 'identity.metadata_public'
              subject_from: 'identity.traits.username'
          noop:
            enabled: true
        authorizers:
          allow:
            enabled: true
        mutators:
          noop:
            enabled: true
          header:
            enabled: true
            config:
              headers:
                x-company-user: '{{ print .Subject }}'
                x-company-user-roles: '{{ print .Extra.roles }}'
                x-company-user-custom-metadata: '{{ print .Extra.customMetadata }}'
    service:
      proxy:
        type: NodePort
        nodePort: 30455
      api:
        type: NodePort
        nodePort: 30456
