# Default values for auth-server.
replicaCount: 1

image:
  repository: auth-server
  pullPolicy: Never
  tag: "v1"

imagePullSecrets: []
nameOverride: "auth-server"
fullnameOverride: "auth-server"

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 3000
  nodePort: 30000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
