apiVersion: v1
kind: ConfigMap
metadata:
  name: oathkeeper-config

data:
  oathkeeper.yml: |
    log:
      level: debug
      format: json
      leak_sensitive_values: true
    serve:
      proxy:
        cors:
          enabled: false
    errors:
      fallback:
        - json
      handlers:
        json:
          enabled: true
          config:
            verbose: true
    # access_rules:
    #  matching_strategy: regexp
    #  repositories:
    #    - file:///etc/config/oathkeeper/access-rules.yml
    authenticators:
      anonymous:
        enabled: true
        config:
          subject: guest
      bearer_token:
        enabled: true
        config:
          check_session_url: http://auth-server:3000/sessions/whoami
          preserve_path: true
          extra_from: 'identity.metadata_public'
          subject_from: 'identity.traits.username'
      noop:
        enabled: true
    authorizers:
      allow:
        enabled: true
    mutators:
      noop:
        enabled: true
      header:
        enabled: true
        config:
          headers:
            x-ant-user: '{{ print .Subject }}'
            x-ant-user-roles: '{{ print .Extra.roles }}'
            x-ant-user-custom-metadata: '{{ print .Extra.customMetadata }}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oathkeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oathkeeper
  template:
    metadata:
      labels:
        app: oathkeeper
    spec:
      containers:
      - name: oathkeeper
        image: oryd/oathkeeper:v0.40.6
        args:
          - serve
          - proxy
          - -c
          - /etc/config/oathkeeper/oathkeeper.yml
        env:
        - name: LOG_LEVEL
          value: debug
        ports:
        - containerPort: 4455
        - containerPort: 4456
        volumeMounts:
        - name: oathkeeper-config
          mountPath: /etc/config/oathkeeper
          readOnly: true
      volumes:
      - name: oathkeeper-config
        configMap:
          name: oathkeeper-config
---
apiVersion: v1
kind: Service
metadata:
  name: oathkeeper
spec:
  selector:
    app: oathkeeper
  ports:
    - name: proxy
      protocol: TCP
      port: 4455
      targetPort: 4455
      nodePort: 30455
    - name: api
      protocol: TCP
      port: 4456
      targetPort: 4456
      nodePort: 30456
  type: NodePort
