apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: auth-poc
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/yourusername/auth-poc
