apiVersion: v1
kind: ConfigMap
metadata:
  name: oathkeeper-config
data:
  oathkeeper.yml: |
    access_rules:
      matching_strategy: regexp
      repositories:
        - file:////etc/config/oathkeeper-rules/oathkeeper-rules.yml

    log:
      level: {{ .Values.config.logLevel }}
      format: json
      leak_sensitive_values: true
    serve:
      proxy:
        cors:
          enabled: false
    errors:
      fallback:
        - json
      handlers:
        json:
          enabled: true
          config:
            verbose: true
    authenticators:
      anonymous:
        enabled: true
        config:
          subject: guest
      bearer_token:
        enabled: true
        config:
          check_session_url: {{ .Values.config.checkSessionUrl }}
          preserve_path: true
          extra_from: 'identity.metadata_public'
          subject_from: 'identity.traits.username'
      noop:
        enabled: true
    authorizers:
      allow:
        enabled: true
    mutators:
      noop:
        enabled: true
      header:
        enabled: true
        config:
          headers:
            x-ant-user: '{{`{{ print .Subject }}`}}'
            x-ant-user-roles: '{{`{{ print .Extra.roles }}`}}'
            x-ant-user-custom-metadata: '{{`{{ print .Extra.customMetadata }}`}}'
