apiVersion: v1
kind: ServiceAccount
metadata:
  name: oathkeeper-maester
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oathkeeper-maester
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["oathkeeper.ory.sh"]
  resources: ["rules"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["oathkeeper.ory.sh"]
  resources: ["rules/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oathkeeper-maester
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oathkeeper-maester
subjects:
- kind: ServiceAccount
  name: oathkeeper-maester
  namespace: default
