apiVersion: v1
kind: Service
metadata:
  name: oathkeeper
spec:
  selector:
    app: oathkeeper
  ports:
    - name: proxy
      protocol: TCP
      port: {{ .Values.service.proxyPort }}
      targetPort: 4455
      nodePort: {{ .Values.service.proxyNodePort }}
    - name: api
      protocol: TCP
      port: {{ .Values.service.apiPort }}
      targetPort: 4456
      nodePort: {{ .Values.service.apiNodePort }}
  type: NodePort
