{{- if .Values.oathkeeper.enabled }}
{{- range $ruleConfigKey, $rule := .Values.oathkeeper.rules }}
{{- if $rule.enabled }}
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: {{ $rule.name | default (printf "%s-%s-rule" (include "generic-chart.fullname" $) $ruleConfigKey) }}
  labels:
    {{- include "generic-chart.labels" $ | nindent 4 }}
spec:
  match:
    url: {{ $rule.urlPattern | quote }}
    methods: {{ $rule.methods | toJson }}
  upstream:
    preserveHost: {{ $rule.upstream.preserveHost | default true }}
    url: {{ $rule.upstream.url | quote }}
  authenticators:
    - handler: {{ $rule.authenticator.handler | quote }}
      {{- if $rule.authenticator.config }}
      config:
        {{- toYaml $rule.authenticator.config | nindent 8 }}
      {{- end }}
  authorizer:
    handler: {{ $rule.authorizer.handler | quote }}
    {{- if $rule.authorizer.config }}
    config:
      {{- toYaml $rule.authorizer.config | nindent 6 }}
    {{- end }}
  mutators:
    - handler: {{ $rule.mutator.handler | quote }}
      {{- if $rule.mutator.config }}
      config:
        {{- toYaml $rule.mutator.config | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}