apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: auth-server-rule
  namespace: ory
spec:
  upstream:
    url: "http://auth-server.default.svc.cluster.local:3000"
  match:
    url: "<https|http>://<.*>/api/json<.*>"
    methods: ["GET", "POST"]
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: myapp-rule
  namespace: ory
spec:
  upstream:
    url: "http://myapp.default.svc.cluster.local:4000"
  match:
    url: "<https|http>://<.*>/api/myapp<.*>"
    methods: ["GET", "POST", "PUT", "PATCH", "DELETE"]
  authenticators:
    - handler: bearer_token
  authorizer:
    handler: allow
  mutators:
    - handler: header

